AllCops:
  Include:
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.rabl'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Debugger:
  Enabled: true

Documentation:
  Enabled: false

EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Encoding:
  EnforcedStyle: when_needed

FileName:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

ParameterLists:
  Enabled: false

Semicolon:
  AllowAsExpressionSeparator: true

SignalException:
  EnforcedStyle: only_raise

SingleLineBlockParams:
  Enabled: false

SingleLineMethods:
  AllowIfMethodIsEmpty: true

StringLiterals:
  EnforcedStyle: false

UnusedBlockArgument:
  Enabled: false

UnusedMethodArgument:
  Enabled: false
